/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crc;

import java.awt.Component;
import java.awt.Container;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Xrhstos
 */
public class CustomizerRndSimulator extends javax.swing.JDialog {

    private Font font;
    private int defaultFontSize;
    /**
     * Creates new form CustomizerRndSimulator
     */
    public CustomizerRndSimulator(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Random Simulator Settings");
        t1.setText(GUI.Options.MSG + "");
        t2.setText(GUI.Options.BIT_1 + "");
        t3.setText(GUI.Options.BIT_2 + "");
        t4.setText(GUI.Options.BER_1 + "");
        t5.setText(GUI.Options.BER_2 + "");
        t6.setText(GUI.Options.DEC_1 + "");
        t7.setText(GUI.Options.DEC_2 + "");
        
        InputStream is = getClass().getResourceAsStream("/Raleway-Regular.ttf");
        try {
            //create the font to use. Specify the size!
            font = Font.createFont(Font.TRUETYPE_FONT, is).deriveFont(12f);
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            //register the font
            ge.registerFont(font);
        } catch (IOException e) {
            e.printStackTrace();
        } catch (FontFormatException e) {
            e.printStackTrace();
        }
        /*
        try {
            font = Font.createFont(Font.TRUETYPE_FONT, is);
        } catch (FontFormatException | IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
        defaultFontSize = 0;
        changeFont(this, font, 0);
        
        UIManager.put("Menu.font", font);
        UIManager.put("MenuItem.font", font);
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        UIManager.put("InternalFrame.titleFont", font);
    }

     public void changeFont(Component component, Font font, int fontSize) {
        Font f = component.getFont();
        component.setFont(new Font(font.getName(), f.getStyle(), f.getSize() + fontSize));
        if (component instanceof Container) {
            for (Component child : ((Container) component).getComponents()) {
                changeFont(child, font, fontSize);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancel = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        okrun = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextArea();
        t4 = new javax.swing.JTextArea();
        t6 = new javax.swing.JTextArea();
        t7 = new javax.swing.JTextArea();
        t3 = new javax.swing.JTextArea();
        t5 = new javax.swing.JTextArea();
        t2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        okrun.setText("OK and Run");
        okrun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okrunActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setBackground(new java.awt.Color(51, 51, 51));
        t1.setColumns(20);
        t1.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        t1.setForeground(new java.awt.Color(255, 0, 255));
        t1.setRows(5);
        t1.setText("10000");
        t1.setToolTipText("1 to x Messages");
        t1.setCaretColor(new java.awt.Color(204, 0, 204));
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 10, 53, 20));

        t4.setBackground(new java.awt.Color(51, 51, 51));
        t4.setColumns(20);
        t4.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        t4.setForeground(new java.awt.Color(255, 0, 255));
        t4.setRows(5);
        t4.setText("0");
        t4.setToolTipText("x: x to y BER (0 <float< 1)");
        t4.setCaretColor(new java.awt.Color(204, 0, 204));
        jPanel1.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 57, 20, 28));

        t6.setBackground(new java.awt.Color(51, 51, 51));
        t6.setColumns(20);
        t6.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        t6.setForeground(new java.awt.Color(255, 0, 255));
        t6.setRows(5);
        t6.setText("8");
        t6.setToolTipText("x: x to y bits for Polynomial");
        t6.setCaretColor(new java.awt.Color(204, 0, 204));
        jPanel1.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 85, 18, 24));

        t7.setBackground(new java.awt.Color(51, 51, 51));
        t7.setColumns(20);
        t7.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        t7.setForeground(new java.awt.Color(255, 0, 255));
        t7.setRows(5);
        t7.setText("1");
        t7.setToolTipText("y: x to y bits for Polynomial");
        t7.setCaretColor(new java.awt.Color(204, 0, 204));
        jPanel1.add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 85, 20, 24));

        t3.setBackground(new java.awt.Color(51, 51, 51));
        t3.setColumns(20);
        t3.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        t3.setForeground(new java.awt.Color(255, 0, 255));
        t3.setRows(5);
        t3.setText("6");
        t3.setToolTipText("y: x to y bits per message");
        t3.setCaretColor(new java.awt.Color(204, 0, 204));
        jPanel1.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 30, 20, 28));

        t5.setBackground(new java.awt.Color(51, 51, 51));
        t5.setColumns(20);
        t5.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        t5.setForeground(new java.awt.Color(255, 0, 255));
        t5.setRows(5);
        t5.setText("0.009");
        t5.setToolTipText("y: x to y BER (0 <float< 1)");
        t5.setCaretColor(new java.awt.Color(204, 0, 204));
        jPanel1.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 58, 65, 27));

        t2.setBackground(new java.awt.Color(51, 51, 51));
        t2.setColumns(20);
        t2.setFont(new java.awt.Font("Open Sans", 0, 12)); // NOI18N
        t2.setForeground(new java.awt.Color(255, 0, 255));
        t2.setRows(5);
        t2.setText("18");
        t2.setToolTipText("x: x to y bits per message");
        t2.setCaretColor(new java.awt.Color(204, 0, 204));
        jPanel1.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 24, 28));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crc/decoder.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 85, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crc/bits.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 31, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crc/ber.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/crc/messages.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jButton1.setText("Default");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 70, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(ok)
                .addGap(100, 100, 100)
                .addComponent(okrun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(okrun)
                    .addComponent(ok))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        // TODO add your handling code here:
        GUI.Options.CUSTOMIZER_INDEX = 0;
        GUI.Options.MSG = Integer.parseInt(t1.getText());
        GUI.Options.BIT_1 = Integer.parseInt(t2.getText());
        GUI.Options.BIT_2 = Integer.parseInt(t3.getText());
        GUI.Options.BER_1 = Double.parseDouble(t4.getText());
        GUI.Options.BER_2 = Double.parseDouble(t5.getText());
        GUI.Options.DEC_1 = Integer.parseInt(t6.getText());
        GUI.Options.DEC_2 = Integer.parseInt(t7.getText());
        this.dispose();
        
    }//GEN-LAST:event_okActionPerformed

    private void okrunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okrunActionPerformed
        // TODO add your handling code here:
        GUI.Options.CUSTOMIZER_INDEX = 1;
        GUI.Options.MSG = Integer.parseInt(t1.getText());
        GUI.Options.BIT_1 = Integer.parseInt(t2.getText());
        GUI.Options.BIT_2 = Integer.parseInt(t3.getText());
        GUI.Options.BER_1 = Double.parseDouble(t4.getText());
        GUI.Options.BER_2 = Double.parseDouble(t5.getText());
        GUI.Options.DEC_1 = Integer.parseInt(t6.getText());
        GUI.Options.DEC_2 = Integer.parseInt(t7.getText());

        this.dispose();
    }//GEN-LAST:event_okrunActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        GUI.Options.CUSTOMIZER_INDEX = 2;
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        t1.setText("10000");
        t2.setText("18");
        t3.setText("6");
        t4.setText("0");
        t5.setText("0.009");
        t6.setText("8");
        t7.setText("1");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomizerRndSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomizerRndSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomizerRndSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomizerRndSimulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomizerRndSimulator dialog = new CustomizerRndSimulator(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton ok;
    private javax.swing.JButton okrun;
    private javax.swing.JTextArea t1;
    private javax.swing.JTextArea t2;
    private javax.swing.JTextArea t3;
    private javax.swing.JTextArea t4;
    private javax.swing.JTextArea t5;
    private javax.swing.JTextArea t6;
    private javax.swing.JTextArea t7;
    // End of variables declaration//GEN-END:variables
}
